//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursBNRService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.infovalutar.ro/", ConfigurationName="CursBNRService.CursSoap")]
    public interface CursSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.infovalutar.ro/GetLatestValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> GetLatestValueAsync(string Moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.infovalutar.ro/getlatestvalue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CursBNRService.getlatestvalueResponse> getlatestvalue1Async(CursBNRService.getlatestvalueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.infovalutar.ro/getall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CursBNRService.getallResponseGetallResult> getallAsync(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.infovalutar.ro/getvalue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> getvalueAsync(System.DateTime TheDate, string Moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.infovalutar.ro/getvalueadv", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CursBNRService.DateValue> getvalueadvAsync(System.DateTime thedate, string themoneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.infovalutar.ro/GetValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CursBNRService.GetValueResponse> GetValue1Async(CursBNRService.GetValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.infovalutar.ro/LastDateInserted", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.DateTime> LastDateInsertedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.infovalutar.ro/lastdateinserted", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CursBNRService.lastdateinsertedResponse> lastdateinserted1Async(CursBNRService.lastdateinsertedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getlatestvalue", WrapperNamespace="http://www.infovalutar.ro/", IsWrapped=true)]
    public partial class getlatestvalueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.infovalutar.ro/", Order=0)]
        public string Moneda;
        
        public getlatestvalueRequest()
        {
        }
        
        public getlatestvalueRequest(string Moneda)
        {
            this.Moneda = Moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getlatestvalueResponse", WrapperNamespace="http://www.infovalutar.ro/", IsWrapped=true)]
    public partial class getlatestvalueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.infovalutar.ro/", Order=0)]
        public double getlatestvalueResult;
        
        public getlatestvalueResponse()
        {
        }
        
        public getlatestvalueResponse(double getlatestvalueResult)
        {
            this.getlatestvalueResult = getlatestvalueResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infovalutar.ro/")]
    public partial class getallResponseGetallResult
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infovalutar.ro/")]
    public partial class DateValue
    {
        
        private System.DateTime dateField;
        
        private double valueField;
        
        private string monedaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValue", WrapperNamespace="http://www.infovalutar.ro/", IsWrapped=true)]
    public partial class GetValueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.infovalutar.ro/", Order=0)]
        public System.DateTime TheDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.infovalutar.ro/", Order=1)]
        public string Moneda;
        
        public GetValueRequest()
        {
        }
        
        public GetValueRequest(System.DateTime TheDate, string Moneda)
        {
            this.TheDate = TheDate;
            this.Moneda = Moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValueResponse", WrapperNamespace="http://www.infovalutar.ro/", IsWrapped=true)]
    public partial class GetValueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.infovalutar.ro/", Order=0)]
        public double GetValueResult;
        
        public GetValueResponse()
        {
        }
        
        public GetValueResponse(double GetValueResult)
        {
            this.GetValueResult = GetValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lastdateinserted", WrapperNamespace="http://www.infovalutar.ro/", IsWrapped=true)]
    public partial class lastdateinsertedRequest
    {
        
        public lastdateinsertedRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lastdateinsertedResponse", WrapperNamespace="http://www.infovalutar.ro/", IsWrapped=true)]
    public partial class lastdateinsertedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.infovalutar.ro/", Order=0)]
        public System.DateTime lastdateinsertedResult;
        
        public lastdateinsertedResponse()
        {
        }
        
        public lastdateinsertedResponse(System.DateTime lastdateinsertedResult)
        {
            this.lastdateinsertedResult = lastdateinsertedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface CursSoapChannel : CursBNRService.CursSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class CursSoapClient : System.ServiceModel.ClientBase<CursBNRService.CursSoap>, CursBNRService.CursSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CursSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CursSoapClient.GetBindingForEndpoint(endpointConfiguration), CursSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CursSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CursSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CursSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CursSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CursSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<double> GetLatestValueAsync(string Moneda)
        {
            return base.Channel.GetLatestValueAsync(Moneda);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CursBNRService.getlatestvalueResponse> CursBNRService.CursSoap.getlatestvalue1Async(CursBNRService.getlatestvalueRequest request)
        {
            return base.Channel.getlatestvalue1Async(request);
        }
        
        public System.Threading.Tasks.Task<CursBNRService.getlatestvalueResponse> getlatestvalue1Async(string Moneda)
        {
            CursBNRService.getlatestvalueRequest inValue = new CursBNRService.getlatestvalueRequest();
            inValue.Moneda = Moneda;
            return ((CursBNRService.CursSoap)(this)).getlatestvalue1Async(inValue);
        }
        
        public System.Threading.Tasks.Task<CursBNRService.getallResponseGetallResult> getallAsync(System.DateTime dt)
        {
            return base.Channel.getallAsync(dt);
        }
        
        public System.Threading.Tasks.Task<double> getvalueAsync(System.DateTime TheDate, string Moneda)
        {
            return base.Channel.getvalueAsync(TheDate, Moneda);
        }
        
        public System.Threading.Tasks.Task<CursBNRService.DateValue> getvalueadvAsync(System.DateTime thedate, string themoneda)
        {
            return base.Channel.getvalueadvAsync(thedate, themoneda);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CursBNRService.GetValueResponse> CursBNRService.CursSoap.GetValue1Async(CursBNRService.GetValueRequest request)
        {
            return base.Channel.GetValue1Async(request);
        }
        
        public System.Threading.Tasks.Task<CursBNRService.GetValueResponse> GetValue1Async(System.DateTime TheDate, string Moneda)
        {
            CursBNRService.GetValueRequest inValue = new CursBNRService.GetValueRequest();
            inValue.TheDate = TheDate;
            inValue.Moneda = Moneda;
            return ((CursBNRService.CursSoap)(this)).GetValue1Async(inValue);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> LastDateInsertedAsync()
        {
            return base.Channel.LastDateInsertedAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CursBNRService.lastdateinsertedResponse> CursBNRService.CursSoap.lastdateinserted1Async(CursBNRService.lastdateinsertedRequest request)
        {
            return base.Channel.lastdateinserted1Async(request);
        }
        
        public System.Threading.Tasks.Task<CursBNRService.lastdateinsertedResponse> lastdateinserted1Async()
        {
            CursBNRService.lastdateinsertedRequest inValue = new CursBNRService.lastdateinsertedRequest();
            return ((CursBNRService.CursSoap)(this)).lastdateinserted1Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CursSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CursSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CursSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.infovalutar.ro/curs.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CursSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.infovalutar.ro/curs.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CursSoap,
            
            CursSoap12,
        }
    }
}
